version: '3.9'

networks:
    localdev:
        name: localdev

services:
    identity-api:
        build:
            context: .
            dockerfile: Trip.Identity.Dockerfile
        restart: always
        ports:
            - "5000:80"
        networks:
            - localdev
    
    creator-api:
        build:
            context: .
            dockerfile: Trip.Creator.Dockerfile
        restart: always
        ports:
            - "7000:80"
        networks:
            - localdev
    
    profile-api:
        build:
            context: .
            dockerfile: Trip.Profile.Dockerfile
        restart: always
        ports:
            - "6000:80"
        networks:
            - localdev
    
    feeds-api:
        build:
            context: .
            dockerfile: Trip.Feeds.Dockerfile
        restart: always
        ports:
            - "8000:80"
        networks:
            - localdev

    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=myuser
            - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'