version: '3.9'

networks:
    dockernetwork:
        name: DockerNetwork

services:
    identity-api:
        build:
            context: .
            dockerfile: Trip.Identity.Dockerfile
        networks:
            - dockernetwork
        depends_on:
            - rabbitmq3
        restart: always
        ports:
            - "5000:80"

    
    creator-api:
        build:
            context: .
            dockerfile: Trip.Creator.Dockerfile
        networks:
            - dockernetwork
        depends_on:
            - rabbitmq3
        restart: always
        ports:
            - "7000:80"
    
    profile-api:
        build:
            context: .
            dockerfile: Trip.Profile.Dockerfile
        networks:
            - dockernetwork
        depends_on:
            - rabbitmq3
        restart: always
        ports:
            - "6000:80"
    
    feeds-api:
        build:
            context: ./FeedsServer/Trip.Feeds.Api/
            dockerfile: Dockerfile
        networks:
            - dockernetwork
        depends_on:
            - rabbitmq3
        restart: always
        ports:
            - "8000:80"


    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3-management
        networks:
            - dockernetwork
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
